# Generated by Django 2.0.7 on 2018-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180714_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('boys', 'boys'), ('girls', 'girls'), ('mixed', 'mixed')], default='mixed', max_length=10),
        ),
    ]
